name: "ARM build"
description: "Compile the project"

on:
  workflow_dispatch:
  pull_request:
    # Pull request events
    types: [synchronize, opened, reopened, ready_for_review]
    
inputs:
  path:
    required: true
    description: "Build project"
    default: .

runs:
  using: "composite"
  steps:
    - name: "Run clang-format"
      shell: bash
      run: |
        make -C ${{ inputs.path }} all
